name: Test and Lint
on:
  push:
    branches: [ main ]
    tags: [ "*" ]
  pull_request:
  workflow_dispatch:
jobs:
  test-and-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - uses: extractions/setup-just@v1

      - name: Lint and run tests
        run: |
          python -m pip install -r poetry
          poetry install
          just lint test
